### ISSUE TITLE
Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by akshaychopra5207** [grafana/terraform-provider-grafana#256] opened 2021-08-04 09:22 UTC
### Terraform Version
Terraform v0.13.4

provider digitalplatform.local/maf/digitalplatform v1.0.1
provider registry.terraform.io/grafana/grafana v1.13.3
provider registry.terraform.io/hashicorp/azurerm v2.43.0
provider registry.terraform.io/hashicorp/http v1.2.0

### Affected Resource(s)
* grafana_dashboard

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
```

resource "grafana_dashboard" "main" {
  count       = length(var.dashboard_properties)
  folder      = "23"
  config_json = templatefile("modules/dashboard/templates/${var.dashboard_properties[count.index].template}.json.tmpl", merge(var.default_dashboard_vars, var.dashboard_properties[count.index].tmplVars, { title = var.dashboard_properties[count.index].name }))
  depends_on  = [digitalplatform_dashboard_datasource.main]
}
```

```
### Debug Output
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: panic: Attempted to unmarshal invalid JSON. This unexpectedly got past schema validation.
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: 
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: goroutine 40 [running]:
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: github.com/grafana/terraform-provider-grafana/grafana.unmarshalDashboardConfigJSON(0x19ba146, 0x24, 0x18747e0)
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         github.com/grafana/terraform-provider-grafana/grafana/resource_dashboard.go:268 +0x106
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: github.com/grafana/terraform-provider-grafana/grafana.normalizeDashboardConfigJSON(0x18747e0, 0xc0000aebd0, 0xb, 0x18747e0)
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         github.com/grafana/terraform-provider-grafana/grafana/resource_dashboard.go:299 +0x145
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diffString(0xc0000aa870, 0x19a4dad, 0xb, 0xc0003b6280, 0xc000375508, 0x1ab41d8, 0xc000175b80, 0x203000, 0x0, 0x0)
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/schema.go:1375 +0x6e3
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0xc0000aa870, 0x19a4dad, 0xb, 0xc0003b6280, 0xc00089a780, 0x1ab41d8, 0xc000175b80, 0x0, 0x0, 0x0)
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/schema.go:957 +0x4e8
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc0000aa870, 0x1ab05b8, 0xc0002e42c0, 0xc0001b2bd0, 0xc000302d80, 0x0, 0x184bce0, 0xc0002c6dc0, 0x1f8ff00, 0x18747e0, ...)
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/schema.go:522 +0x219
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0xc0003b4380, 0x1ab05b8, 0xc0002e42c0, 0xc0001b2bd0, 0xc000302d80, 0x184bce0, 0xc0002c6dc0, 0x0, 0x0, 0x0)
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:506 +0xa5
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc0000da078, 0x1ab05b8, 0xc0002e42c0, 0xc0002d6b90, 0xc0002e42c0, 0x1963d60, 0xc0002dab00)
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:693 +0x7c5
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).PlanResourceChange(0xc00082c580, 0x1ab0660, 0xc0002e42c0, 0xc0001b29a0, 0xc00082c580, 0xc0002dab40, 0xc000525ba0)
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:315 +0xb5
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler(0x1963d60, 0xc00082c580, 0x1ab0660, 0xc0002dab40, 0xc0000a8840, 0x0, 0x1ab0660, 0xc0002dab40, 0xc000526000, 0xa3b4)
2021-08-04T13:15:35.979+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:362 +0x214
2021-08-04T13:15:35.980+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00027c8c0, 0x1ab7f58, 0xc000135500, 0xc00022c360, 0xc000302690, 0x1f51088, 0x0, 0x0, 0x0)
2021-08-04T13:15:35.980+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         google.golang.org/grpc@v1.38.0/server.go:1286 +0x52b
2021-08-04T13:15:35.980+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: google.golang.org/grpc.(*Server).handleStream(0xc00027c8c0, 0x1ab7f58, 0xc000135500, 0xc00022c360, 0x0)
2021-08-04T13:15:35.980+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         google.golang.org/grpc@v1.38.0/server.go:1609 +0xd0c
2021-08-04T13:15:35.980+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000b6210, 0xc00027c8c0, 0x1ab7f58, 0xc000135500, 0xc00022c360)
2021-08-04T13:15:35.980+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         google.golang.org/grpc@v1.38.0/server.go:934 +0xab
2021-08-04T13:15:35.980+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-08-04T13:15:35.980+0400 [DEBUG] plugin.terraform-provider-grafana_v1.13.3:         google.golang.org/grpc@v1.38.0/server.go:932 +0x1fd
2021-08-04T13:15:35.981+0400 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-08-04T13:15:35.982+0400 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/grafana/grafana/1.13.3/darwin_amd64/terraform-provider-grafana_v1.13.3 pid=90788 error="exit status 2"
2021/08/04 13:15:35 [ERROR] eval: *terraform.EvalDiff, err: rpc error: code = Unavailable desc = transport is closing
2021/08/04 13:15:35 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.
Error: rpc error: code = Unavailable desc = transport is closing

### Expected Behavior
What should have happened?

### Actual Behavior
Terraform plan failed
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
terraform init
terraform appy
### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
https://github.com/grafana/terraform-provider-grafana/issues/238
https://github.com/grafana/terraform-provider-grafana/issues/249

**Comment by ghmeier** [comment] 2021-10-05 20:30
Hey - this looks like a duplicate of #238 can you confirm? It looks like this is consistently causing crashes still. I see you've commented there. It seems like we should address it all in the same issue.

**Comment by julienduchesne** [comment] 2022-02-21 13:16
That panic was fixed here: https://github.com/grafana/terraform-provider-grafana/issues/246 and the provider has changed a lot since then. Please open a new issue if you reencounter this

**Closed as completed by julienduchesne** 2022-02-21 13:16 UTC
