### ISSUE TITLE
Configure cachingConfig through the provider configuration

### ISSUE THREAD

**Issue by rpriyanshu9** [grafana/terraform-provider-grafana#1021] opened 2023-09-05 16:11 UTC
Currently all backend datasources support caching through datasource configuration - https://grafana.com/docs/grafana/latest/administration/data-source-management/#query-and-resource-caching. We can configure caching from the UI at the moment, but I was not able to find a way to do the same via terraform (grafana provider).

`cachingConfig` param ref: https://github.com/grafana/grafana/blob/cc1205d6ba19df2b93de89e74888d83039c2508f/packages/grafana-data/src/types/datasource.ts#L622-L655

**Comment by julienduchesne** [comment] 2023-10-18 20:15
Duplicate of https://github.com/grafana/terraform-provider-grafana/issues/765

**Closed as not planned by julienduchesne** 2023-10-18 20:15 UTC
