### ISSUE TITLE
folder lifecycle ignore_changes does not work for url

### ISSUE THREAD

**Issue by klubi** [grafana/terraform-provider-grafana#803] opened 2023-02-02 12:03 UTC
### Terraform Version
* Terraform: 1.3.3
* Terraform Grafana Provider: 1.33.0
* Grafana: 8.3.4

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_folder

### Terraform Configuration Files
```tf
locals {
  folders  = var.folders_override == null ? distinct(flatten([for _, v in flatten(fileset("${path.module}/source", "*/*.json")) : dirname(v)])) : var.folders_override
}

resource "grafana_folder" "folder" {
  for_each = { for f in local.folders : f => f }
  title    = each.key
  uid      = each.key

  lifecycle {
    ignore_changes = [
      url,
    ]
  }
}
```

My grafana instance can be accessed using two URL's, one is used to access it locally, and one from CICD environment.
I'm woking with terragrunt, which configures URL and KEY for provider depending on where plan/apply is executed.
When I apply changes from one of them, and then try doing the same from another they constantly try changing the folder URL despite `lifecycle` `ignore_changes` is used.
When I add another field to `ignore_changes` then it's ignored as desired. Issue seems to only be related to `url`.

**Comment by julienduchesne** [comment] 2023-02-02 20:54
Since URL is a completely computed attribute, it cannot be ignored. `ignore_changes` is used to avoid applying when a given attribute changes, it does not work to prevent Terraform from _reading_ values

If you want to have a URL that is agnostic to which host you are applying with, you can split your URL and build it yourself:

```
locals {
   local my_grafana_url = "https://grafana.org.com"
   # from https://github.com/hashicorp/terraform/issues/23893#issuecomment-577963377
   url_regex  = "(?:(?P<scheme>[^:/?#]+):)?(?://(?P<authority>[^/?#]*))?(?P<path>[^?#]*)(?:\\?(?P<query>[^#]*))?(?:#(?P<fragment>.*))?"
   folder_url = local.my_grafana_url + regex(local.url_regex, grafana_folder.test.url).path
}
```

I'll close this issue because this is not a bug in the provider. It is working as designed

**Closed as completed by julienduchesne** 2023-02-02 20:54 UTC

**Comment by klubi** [comment] 2023-02-03 08:52
@julienduchesne can you elaborate more on this?

I tried setting value of folder URL, but I'm getting 
```
Can't configure a value for "url": its value will be decided automatically based on the result of applying this configuration.
```

```yaml
resource "grafana_folder" "folder" {
  for_each = { for f in local.folders : f => f }
  title    = each.key
  uid      = each.key
  url      = "${var.grafana_url}/dashboards/f/${each.key}/${lower(each.key)})"
}
```

So I don't actually understand how I can set it.
