### ISSUE TITLE
Grafana Cloud broken ip for grafana_folder resources

### ISSUE THREAD

**Issue by jcortejoso** [grafana/terraform-provider-grafana#465] opened 2022-04-22 16:02 UTC
### Terraform Version
* Terraform: 1.1.8
* Terraform Grafana Provider: 1.21.1
* Grafana: Grafana Cloud

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_folder

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "grafana_folder" "folders" {
  for_each = toset(distinct([for d in fileset("${path.module}/files/grafana/dashboards", "*/*.json") : dirname(d)]))

  title = title(each.key)
}
```

### Debug Output
https://gist.github.com/jcortejoso/b5540250bbdf32ba812dc3c1a20de67a

### Expected Behavior
What should have happened?
Terraform grafana provider can create/read/manage the state of grafana folders normally.

### Actual Behavior
What actually happened?
The provider has deleted all the folders we had in the state. Also it cannot create new folder now showing the error:
```
Provider produced inconsistent result after apply
```
It seems the reason is that endpoint `/api/folders/id/{id}` is not longer available.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?
Running on Grafana Cloud.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by julienduchesne** [comment] 2022-04-22 16:08
Duplicate of https://github.com/grafana/terraform-provider-grafana/issues/463

**Closed as completed by julienduchesne** 2022-04-22 16:08 UTC
