### ISSUE TITLE
[Bug]: grafana_folder_permission [GET /access-control/{resource}/{resourceID}] getResourcePermissions (status 400): {}

### ISSUE THREAD

**Issue by charltonstanley** [grafana/terraform-provider-grafana#1454] opened 2024-03-28 22:49 UTC
### Terraform Version

1.7.5

### Terraform Grafana Provider Version

2.9.0+

### Grafana Version

9.4.7

### Affected Resource(s)

grafana_folder_permission

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    grafana = {
      version = "2.9.0"
      source = "grafana/grafana"
    }
  }
}

provider "grafana" {
  url  = "<grafana-oss-url>"
  auth = <my_auth_token>
}

resource "grafana_team" "team" {
  name = "Team Name"
}

resource "grafana_folder" "collection" {
  title = "Folder Title"
}

resource "grafana_folder_permission" "collectionPermission" {
  folder_uid = grafana_folder.collection.uid
  permissions {
    role       = "Editor"
    permission = "Edit"
  }
  permissions {
    team_id    = grafana_team.team.id
    permission = "View"
  }
}

```

### Expected Behavior

```
data.terraform_remote_state.grafana_poc: Reading...
data.terraform_remote_state.grafana_poc: Read complete after 2s

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # grafana_folder.collection will be created
  + resource "grafana_folder" "collection" {
      + id                           = (known after apply)
      + prevent_destroy_if_not_empty = false
      + title                        = "Folder Title"
      + uid                          = (known after apply)
      + url                          = (known after apply)
    }

  # grafana_folder_permission.collectionPermission will be created
  + resource "grafana_folder_permission" "collectionPermission" {
      + folder_uid = (known after apply)
      + id         = (known after apply)

      + permissions {
          + permission = "Edit"
          + role       = "Editor"
          + team_id    = "0"
          + user_id    = "0"
        }
      + permissions {
          + permission = "View"
          + team_id    = (known after apply)
          + user_id    = "0"
        }
    }

  # grafana_team.team will be created
  + resource "grafana_team" "team" {
      + id                               = (known after apply)
      + ignore_externally_synced_members = true
      + name                             = "Team Name"
      + team_id                          = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

grafana_folder.collection: Creating...
grafana_team.team: Creating...
grafana_folder.collection: Creation complete after 0s [id=0:35]
grafana_team.team: Creation complete after 0s [id=1:3]
grafana_folder_permission.collectionPermission: Creating...
grafana_folder_permission.collectionPermission: Creation complete after 1s [id=0:kQQcF4xSk]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

### Actual Behavior

```
data.terraform_remote_state.grafana_poc: Reading...
data.terraform_remote_state.grafana_poc: Read complete after 1s

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # grafana_folder.collection will be created
  + resource "grafana_folder" "collection" {
      + id                           = (known after apply)
      + prevent_destroy_if_not_empty = false
      + title                        = "Folder Title"
      + uid                          = (known after apply)
      + url                          = (known after apply)
    }

  # grafana_folder_permission.collectionPermission will be created
  + resource "grafana_folder_permission" "collectionPermission" {
      + folder_uid = (known after apply)
      + id         = (known after apply)

      + permissions {
          + permission = "Edit"
          + role       = "Editor"
          + team_id    = "0"
          + user_id    = "0"
        }
      + permissions {
          + permission = "View"
          + team_id    = (known after apply)
          + user_id    = "0"
        }
    }

  # grafana_team.team will be created
  + resource "grafana_team" "team" {
      + id                               = (known after apply)
      + ignore_externally_synced_members = true
      + name                             = "Team Name"
      + team_id                          = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

grafana_folder.collection: Creating...
grafana_team.team: Creating...
grafana_folder.collection: Creation complete after 0s [id=0:36]
grafana_team.team: Creation complete after 1s [id=1:4]
grafana_folder_permission.collectionPermission: Creating...
╷
│ Error: [GET /access-control/{resource}/{resourceID}] getResourcePermissions (status 400): {}
│ 
│   with grafana_folder_permission.collectionPermission,
│   on main.tf line 9, in resource "grafana_folder_permission" "collectionPermission":
│    9: resource "grafana_folder_permission" "collectionPermission" {
│ 
╵
```

### Steps to Reproduce

Launch a non-enterprise Amazon Managed Grafana workspace
run the above code excerpt
observe the error

### Important Factoids

#1293 switched the `grafana_folder_permission` resource to the new RBAC API. According to the [RBAC HTTP API documentation](https://grafana.com/docs/grafana/latest/developers/http_api/access_control/), this API is only available for grafana enterprise or cloud users.  Could this be switched to use the [Folder Permissions API](https://grafana.com/docs/grafana/latest/developers/http_api/folder_permissions/) instead? There was a reference in the PR about the old API being deprecated. I don't know if that was referring to the Folder Permissions API or not, but as far as i can tell, there is no deprecation notice on that page. 

I'm happy to provide more details if needed, just lmk.

```[tasklist]
### Tasks
```

**Comment by julienduchesne** [comment] 2024-04-02 12:01
Sorry but I'll have to close this

This is a duplicate of https://github.com/grafana/terraform-provider-grafana/issues/1302. We will, unfortunately, not support an old API because AMG disables RBAC (see https://github.com/aws/amazon-managed-grafana-roadmap/issues/69). 

Also, 9.4.7 is not a version that is actively maintained in the TF provider. We support the latest v8, the latest v9 (v9.5.18) as well as the latest v10 patches.

The only thing I can think of to fix this is to stay on the old TF version (like Amazon is staying on an old Grafana version 🤷)

**Closed as not planned by julienduchesne** 2024-04-02 12:01 UTC
Labels: triage
