### ISSUE TITLE
Terraform not able to destroy resources in order to recreate them after Grafana folder name change

### ISSUE THREAD

**Issue by shalyng** [grafana/terraform-provider-grafana#85] opened 2020-01-08 22:21 UTC
### Terraform Version
Terraform v0.12.18
+ provider.grafana v1.5.0

Have also tried:

Terraform v0.12.9
+ provider.grafana v1.5.0

### Affected Resource(s)
(in separate instances)
- grafana_dashboard
- grafana_folder

### Terraform Configuration Files
```hcl
terraform {
  backend "s3" {
    bucket = "example-bucket"
    key    = "rest-of/path-to/dashboards-statefile.tfstate"
    region = "us-east-1"
  }
}

locals {
  dashboard_dir = "${path.module}/../../dashboard_directory"
}

provider "grafana" {
  url  = "https://grafana.url.here.com"
  auth = var.grafana_api_key
}

resource "grafana_folder" "grafana_folder" {
  title = "Grafana Folder"
}

resource "grafana_dashboard" "dashboard" {
  for_each    = fileset("${local.dashboard_dir}/", "*")
  config_json = jsonencode(jsondecode(file("${local.dashboard_dir}/${each.value}")))
  folder      = grafana_folder.grafana_folder.id
}
```

### Debug Output
Omitting majority for brevity but here is an example of what I'm seeing. Note that this is not happening to all dashboards. For some reason there are a couple that seem to not have a problem.

```
2020/01/08 15:54:40 [DEBUG] grafana_dashboard.grafana_dashboard["dashboard_config.json"]: apply errored, but we're indicating that via the Error pointer rather than returning it: 412 Precondition Failed
2020/01/08 15:54:40 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/01/08 15:54:40 [TRACE] EvalWriteState: writing current state object for grafana_dashboard.grafana_dashboard["dashboard_config.json"]
2020/01/08 15:54:40 [TRACE] <root>: eval: *terraform.EvalApplyPost
2020/01/08 15:54:40 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: 412 Precondition Failed
2020/01/08 15:54:40 [ERROR] <root>: eval: *terraform.EvalSequence, err: 412 Precondition Failed
2020/01/08 15:54:40 [ERROR] <root>: eval: *terraform.EvalOpFilter, err: 412 Precondition Failed
2020/01/08 15:54:40 [TRACE] [walkApply] Exiting eval tree: grafana_dashboard.grafana_dashboard["dashboard_config.json"] (destroy)
2020/01/08 15:54:40 [TRACE] vertex "grafana_dashboard.grafana_dashboard[\"dashboard_config.json\"] (destroy)": visit complete
```

### Panic Output
N/A

### Expected Behavior
All dashboard resources (8 in total) should have been destroyed and recreated with the state being updated.

### Actual Behavior
Majority of the dashboards fail to destroy (in order to be recreated), 412 Precondition failed errors appear and the statefile is not updated.

### Steps to Reproduce
1. Have statefile in good condition with a folder and dashboard(s) in said folder.
2. Change name of grafana folder in terraform file.
3. Run `terraform plan` and see dashboards and folder will all be destroyed and then created.
4. Run `terraform apply` and get `412 Precondition Failed` errors (sometimes one for each dashboard, but I've also seen some dashboards not have any problem for some reason).

### Important Factoids
Steps and behaviors laid out above are when editing the grafana_folder resource. The same has happened with grafana_dashboard resources as well. We were having issues adding new dashboards to our existing folder (in statefile), but this was fixed by encoding and decoding the json to cause it to not find any changes with the config file (there never were changes with it, but terraform thought there were).

### References
N/A

**Comment by mlclmj** [comment] 2020-04-18 05:21
Hey @shalyng -- this doesn't shock me, I have a vague memory of folders being flaky in the past. I'll take a look and see if I can figure anything out but feel free to update the issue/file a PR if you find the cause

**Comment by anGie44** [comment] 2020-06-02 06:20
hi @shalyng @mlclmj , which version of Grafana server are you running? I noticed the API method used in the provider to destroy dashboards (`DeleteDashboard`) is deprecated for 5.0+ (it's now `DeleteDashboardByUID`) ..not sure if it's possibly related to your issue on forcenew since it sounds like maybe a couple of dashboards do in fact get destroyed?

**Comment by shalyng** [comment] 2020-06-02 14:24
We're at v6.7.3 right now. Hard to say exact version back in January, but it was definitely v6.

**Comment by tonglil** [comment] 2020-06-03 22:59
Thanks, this should be fixed with https://github.com/terraform-providers/terraform-provider-grafana/pull/84#pullrequestreview-423220797 by changing to use the UID now that it is upstream.

Waiting ont he upstream to be updated to `DeleteDashboardbyUid`: https://github.com/nytm/go-grafana-api/pull/45

**Comment by inkel** [comment] 2021-12-23 18:05
I've tested a similar with the following versions and it works:

```
$ terraform version
Terraform v1.1.2
on darwin_amd64
+ provider registry.terraform.io/grafana/grafana v1.17.0
```

If this issue still happens to you using the latest versions please feel free to reopen.

**Closed as completed by inkel** 2021-12-23 18:05 UTC
