### ISSUE TITLE
Generated alerts are not editable in Grafana UI

### ISSUE THREAD

**Issue by HartmannVolker** [grafana/terraform-provider-grafana#727] opened 2022-11-21 16:05 UTC
### Terraform Version
* Terraform:  1.2.9
* Terraform Grafana Provider: 1.30.0
* Grafana: 9.1.6

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_rule_group

### Expected Behavior
After an alert as been created using the terrform provider I can still edit it in the UI (e.g. for short notice changes, or for testing purposes)

### Actual Behavior
I'm not able to make any adjustments to the generated alerts. Alerts can only be viewed, but not edited.
![image](https://user-images.githubusercontent.com/23318693/203101708-48c5c1fa-7101-4f20-a81e-433bcb814e7d.png)

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- Probably related issue in grafana: https://github.com/grafana/grafana/issues/51211
-

**Comment by julienduchesne** [comment] 2022-11-21 19:59
Duplicate of https://github.com/grafana/terraform-provider-grafana/issues/697

**Closed as not planned by julienduchesne** 2022-11-21 19:59 UTC
