### ISSUE TITLE
Contact points no change if slack webhook URL is updated (url)

### ISSUE THREAD

**Issue by brianxu7985** [grafana/terraform-provider-grafana#851] opened 2023-03-13 01:39 UTC
### Terraform Version
* Terraform: v1.3.7
* Terraform Grafana Provider: 1.35.0 / 1.36.0 / 1.36.1
* Grafana: v9.3.6

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_contact_point

~~If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.~~

### Terraform Configuration Files
```hcl
resource "grafana_contact_point" "alert_slack" {
  count = var.enable_slack ? 1 : 0
  name = var.slack_name

  slack {
    disable_resolve_message = false
    url = var.slack_url
    title = var.slack_message_title
    text = var.slack_message_body
  }
}

resource "grafana_contact_point" "alert_pagerduty_slack" {
  count = alltrue([
    var.enable_pagerduty,
    var.enable_slack,
  ]) ? 1 : 0

  name = var.pagerduty_slack_name

  pagerduty {
    disable_resolve_message = false
    integration_key = var.pagerduty_integration_key
    summary = var.pagerduty_summary
  }

  slack {
    disable_resolve_message = false
    url = var.slack_url
    title = var.slack_message_title
    text = var.slack_message_body
  }
}
```

### Debug Output
Output is quite simple. Terraform prompts "No changes. Your infrastructure matches the configuration." 

### Expected Behavior
If url (webHook ULR) is changed, slack contact point should be updated.

### Actual Behavior
No change is detected and previous slack URL is remained.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create slack contact point with slack webHook URL (slack_url_1)
2. `terraform apply`
3. Update var.slack_url
4. `terraform apply` again

### Important Factoids
No

### References
No

**Comment by brianxu7985** [comment] 2023-03-13 01:52
Hi, there:

Seems this is a bug for grafana provider. I am not sure whether there is any specific configuration to update slack webhook URL. If there is, please give me a hint.

Thanks a lot.

**Comment by brianxu7985** [comment] 2023-03-13 04:07
Even I marked variable slack_url to be `sensitive = true`, it's still not updated :(

**Comment by julienduchesne** [comment] 2023-03-16 12:56
This is a duplicate of https://github.com/grafana/terraform-provider-grafana/issues/713, all secret values do not update in this resource

**Closed as not planned by julienduchesne** 2023-03-16 12:56 UTC
